---
title: 'PRONET - Simulation study'
author: "Mariella Gregorich"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  bookdown::html_document2:
    css: "css_style.css"
    theme: cosmo
    number_sections: true
    keep_md: no
    fig_caption: true
    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float: 
      collapsed: true
      smooth_scroll: true
    highlight: tango
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning=F, message=F)

source(here::here("main","functions_main.R"))
source(here::here("main","functions_aux.R"))
source(here::here("main","setup.R"))

# Paths
out.path <- "output"
sim.file <- "sim_2022-04-21/"              #paste0("sim_", Sys.Date(),"/")
sim.path <- here::here(out.path, sim.file)
```

```{r}
# Summarize all scenarios
sim.files <- list.files(sim.path, pattern = "sim_")
sim.all <- lapply(sim.files, function(x) cbind_results(x, sim.path))
tbl_scens <- do.call(rbind, sim.all)

saveRDS(tbl_scens, here::here(sim.path, "tbl_scenarios_results.rds"))  
write.xlsx(tbl_scens, here::here(sim.path, "tbl_scenarios_results.xlsx"), overwrite = T)
```

```{r}
# Preprocess
tbl_scens <- tbl_scens %>%
  mutate_at(vars(dg.thresh), as.factor)
```

# Simulation setup info

The following parameter were included to create the semi-factorial simulation setup:
```{r echo=FALSE}
source2 <- function(file, start, end, ...) {
    file.lines <- scan(file, what=character(), skip=start-1, nlines=end-start+1, sep='\n')
    file.lines.collapsed <- paste(file.lines, collapse='\n')
    source(textConnection(file.lines.collapsed), ...)
}

source2(here::here("main","setup.R"), start=18, end=35, echo = T, prompt.echo = "", spaced = F)
```



# Graphical assessment of results
```{r, echo=F, warning=F, message=F, fig.align='center', fig.width=8, fig.height=6, fig.cap="RMSE for ThreshMethod = trim and eps.y = 0.5"}
tbl_scens %>%
  filter(ThreshMethod %in% "trim" & eps.y == 0.5 &!(AnaMethod %in% "Oracle")) %>%
  ggplot(aes(x=dg.thresh, y=RMSE.est, group=AnaMethod, col=AnaMethod)) +
  geom_ribbon(aes(x=dg.thresh, ymax=RMSE.up, ymin=RMSE.lo, fill=AnaMethod), linetype=2,alpha=.05) +
  geom_line() +
  geom_point() +
  scale_x_discrete("True threshold in data generation") +
  scale_y_continuous("RMSE") +
  facet_grid(SparsMethod~beta.params) +
  theme_bw() +
  theme(text = element_text(size=12))
```

<br>

```{r, echo=F, warning=F, message=F, fig.align='center', fig.width=8, fig.height=6, fig.cap="RMSE for ThreshMethod = trim and eps.y = 0.75"}
tbl_scens %>%
  filter(ThreshMethod %in% "trim" & eps.y == 0.75  & !(AnaMethod %in% "Oracle")) %>%
  ggplot(aes(x=dg.thresh, y=RMSE.est, group=AnaMethod, col=AnaMethod)) +
  geom_ribbon(aes(x=dg.thresh, ymax=RMSE.up, ymin=RMSE.lo, fill=AnaMethod), linetype=2,alpha=.05) +
  geom_line() +
  scale_x_discrete("True threshold in data generation") +
  scale_y_continuous("RMSE") +
  geom_point() +
  facet_grid(SparsMethod~beta.params) +
  theme_bw() +
  theme(text = element_text(size=12))
```

<br>

```{r, echo=F, warning=F, message=F, fig.align='center', fig.width=8, fig.height=6, fig.cap="RMSE for ThreshMethod = trim and eps.y = 1"}
tbl_scens %>%
  filter(ThreshMethod %in% "trim" & eps.y ==1 & !(AnaMethod %in% "Oracle")) %>%
  ggplot(aes(x=dg.thresh, y=RMSE.est, group=AnaMethod, col=AnaMethod)) +
  geom_ribbon(aes(x=dg.thresh, ymax=RMSE.up, ymin=RMSE.lo, fill=AnaMethod), linetype=2,alpha=.05) +
  geom_line() +
  geom_point() +
  scale_x_discrete("True threshold in data generation") +
  scale_y_continuous("RMSE") +
  facet_grid(SparsMethod~beta.params) +
  theme_bw() +
  theme(text = element_text(size=12))
```

<br>

```{r, echo=F, warning=F, message=F, fig.align='center', fig.width=8, fig.height=6, fig.cap="RMSE for ThreshMethod = trim and dg.thresh = 0.4"}
tbl_scens %>%
  filter(ThreshMethod %in% "trim" & dg.thresh ==0.4 & !(AnaMethod %in% "Oracle")) %>%
  ggplot(aes(x=eps.y, y=RMSE.est, group=AnaMethod, col=AnaMethod)) +
  geom_ribbon(aes(x=eps.y, ymax=RMSE.up, ymin=RMSE.lo, fill=AnaMethod), linetype=2,alpha=.05) +
  geom_line() +
  geom_point() +
  scale_x_discrete( expression(epsilon[Y])) +
  scale_y_continuous("RMSE") +
  facet_grid(SparsMethod~beta.params) +
  theme_bw() +
  theme(text = element_text(size=12))
```

