---
title: 'PRONET - Simulation study'
author: "Mariella Gregorich"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  bookdown::html_document2:
    css: "css_style.css"
    theme: cosmo
    number_sections: true
    keep_md: no
    fig_caption: true
    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float: 
      collapsed: true
      smooth_scroll: true
    highlight: tango
---


```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = F, warning=F, message=F)

source(here::here("src","functions_main.R"))
source(here::here("src","functions_aux.R"))
source(here::here("src","setup.R"))

# Paths
out.path <- "output"
sim.date <- "2022-08-01" # Sys.Date()
sim.file <- paste0("sim_", sim.date,"/")
sim.path <- here::here(out.path, sim.file)

# Read in results
tbl_scens <- readRDS(here::here(sim.path, "tbl_scenarios_results.rds"))

# Conditional chunk execution
eval_dgthresh <- length(unique(tbl_scens$dg.thresh))>1
```


```{r}
# Preprocess
tbl_scens <- tbl_scens %>%
  mutate_at(vars(dg.thresh, eps.g, eps.y), as.factor) %>%
  mutate(dg.thresh=ifelse(str_detect(dg.thresh, "single"), "single", 
                          ifelse(str_detect(dg.thresh, "quadratic"), "quadratic", "random")))
 # mutate(beta.params=fct_relevel(beta.params, c("c(2, 4)","c(4, 4)","c(4, 2)")))
```


# Simulation setup info

The following parameter were included to create the semi-factorial simulation setup:
```{r echo=FALSE}
tmp <- read.table(here::here(sim.path, list.files(sim.path, pattern = "info_")[1]))
tmp <- str_split_fixed(tmp[19:37,], pattern = "#", n=2)
  
tmp %>% 
  data.frame() %>%
  `colnames<-`(c("Code", "Explanation")) %>%
  kbl(caption="Parameters for the semi-factorial simulation setup", escape = F) %>%
  kable_classic(full_width = T, html_font = "Calibri")%>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F, position = "left",fixed_thead = T)
```



# Graphical assessment of results

## RMSE

```{r, echo=F, warning=F, message=F, fig.align='center', fig.width=8, fig.height=8, fig.cap="Nested loop plot for RMSE with noise of Y = 0"}
tbl_loo1 <- tbl_scens %>%
  filter(ThreshMethod == "bin" & eps.y==0 & SparsMethod == "weight-based") %>%
  dplyr::select(n, p, dg.thresh, eps.g,AnaMethod, RMSE.est) %>%
  pivot_wider(id_cols = c(n, p, dg.thresh, eps.g), names_from = AnaMethod, values_from = RMSE.est) %>% 
  mutate(n = as.factor(n))

p = nested_loop_plot(resdf = tbl_loo1,
                     x = "n", steps = "eps.g",
                     grid_rows = "p", grid_cols = "dg.thresh",
                     steps_y_base = -0.05, steps_y_height = 0.025,
                     x_name = "Sample size", y_name = "RMSE",
                     spu_x_shift = 1.5,
                     colors = scales::brewer_pal(palette = "Dark2"),
                     steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                     hline_intercept = 0,
                     y_expand_add = c(0.2, 0.05),
                     post_processing = list(
                         add_custom_theme = list(
                           text=element_text(size=12),
                             axis.text.x = element_text(angle = -90,
                                                        vjust = 0.5,
                                                        size = 8)
                         )
                     ))
print(p)
```

<br>

```{r, echo=F, warning=F, message=F, fig.align='center', fig.width=10, fig.height=8, fig.cap="Nested line plot for RMSE for DG threshold scenario single"}
tbl_scens %>%
  filter(eps.y==0 & ThreshMethod=="bin" & dg.thresh == "single") %>%
  mutate_at(vars(beta.params, SparsMethod, AnaMethod), as.factor) %>%
  ggplot(aes(x=n, y=RMSE.est, group=AnaMethod, col=AnaMethod)) +
  geom_ribbon(aes(x=n, ymax=RMSE.up, ymin=RMSE.lo, fill=AnaMethod), linetype=2,alpha=.05) +
  geom_line() +
  geom_point() +
  scale_x_discrete("Sample size") +
  scale_y_continuous("RMSE") +
  facet_nested(p ~SparsMethod+ eps.g) +
  theme_bw() +
  theme(text = element_text(size=12))
```

<br>

```{r, echo=F, warning=F, message=F, fig.align='center', fig.width=10, fig.height=8, fig.cap="Nested line plot for RMSE for DG threshold scenario random"}
tbl_scens %>%
  filter(eps.y==0 & ThreshMethod=="bin" & dg.thresh == "random") %>%
  mutate_at(vars(beta.params, SparsMethod, AnaMethod), as.factor) %>%
  ggplot(aes(x=n, y=RMSE.est, group=AnaMethod, col=AnaMethod)) +
  geom_ribbon(aes(x=n, ymax=RMSE.up, ymin=RMSE.lo, fill=AnaMethod), linetype=2,alpha=.05) +
  geom_line() +
  geom_point() +
  scale_x_discrete("Sample size") +
  scale_y_continuous("RMSE") +
  facet_nested(p ~SparsMethod+ eps.g) +
  theme_bw() +
  theme(text = element_text(size=12))
```

<br>


```{r, echo=F, warning=F, message=F, fig.align='center', fig.width=10, fig.height=8, fig.cap="Nested line plot for RMSE for DG threshold scenario single"}
tbl_scens %>%
  filter(eps.y==0 & ThreshMethod=="bin" & dg.thresh == "quadratic") %>%
  mutate_at(vars(beta.params, SparsMethod, AnaMethod), as.factor) %>%
  ggplot(aes(x=n, y=RMSE.est, group=AnaMethod, col=AnaMethod)) +
  geom_ribbon(aes(x=n, ymax=RMSE.up, ymin=RMSE.lo, fill=AnaMethod), linetype=2,alpha=.05) +
  geom_line() +
  geom_point() +
  scale_x_discrete("Sample size") +
  scale_y_continuous("RMSE") +
  facet_nested(p ~SparsMethod+ eps.g) +
  theme_bw() +
  theme(text = element_text(size=12))
```

<br>


```{r, echo=F, warning=F, message=F, fig.align='center', fig.width=10, fig.height=8, fig.cap="Nested line plot for RMSE for all DG threshold scenarios and no noise for Y or G"}
tbl_scens %>%
  filter(eps.y==0 & eps.g==0 & ThreshMethod=="bin") %>%
  mutate_at(vars(beta.params, SparsMethod, AnaMethod), as.factor) %>%
  ggplot(aes(x=n, y=RMSE.est, group=AnaMethod, col=AnaMethod)) +
  geom_ribbon(aes(x=n, ymax=RMSE.up, ymin=RMSE.lo, fill=AnaMethod), linetype=2,alpha=.05) +
  geom_line() +
  geom_point() +
  scale_x_discrete("Sample size") +
  scale_y_continuous("RMSE") +
  facet_nested(p ~SparsMethod + dg.thresh) +
  theme_bw() +
  theme(text = element_text(size=12))
```

```{r, echo=F, warning=F, message=F, fig.align='center', fig.width=10, fig.height=8, fig.cap="Nested line plot for RMSE for all DG threshold scenarios and maximal noise for Y (epsY=1) and G (epsG=0.1)"}
tbl_scens %>%
  filter(eps.y==1 & eps.g==0.1 & ThreshMethod=="bin") %>%
  mutate_at(vars(beta.params, SparsMethod, AnaMethod), as.factor) %>%
  ggplot(aes(x=n, y=RMSE.est, group=AnaMethod, col=AnaMethod)) +
  geom_ribbon(aes(x=n, ymax=RMSE.up, ymin=RMSE.lo, fill=AnaMethod), linetype=2,alpha=.05) +
  geom_line() +
  geom_point() +
  scale_x_discrete("Sample size") +
  scale_y_continuous("RMSE") +
  facet_nested(p ~SparsMethod + dg.thresh) +
  theme_bw() +
  theme(text = element_text(size=12))
```

```{r, echo=F, warning=F, message=F, fig.align='center', fig.width=10, fig.height=8, fig.cap="Nested line plot for RMSE assessing changes due to varying noise levels in minimal sample size and node size"}
tbl_scens %>%
  filter(n==100 & p==50 & ThreshMethod=="bin") %>%
  mutate_at(vars(beta.params, SparsMethod, AnaMethod), as.factor) %>%
  ggplot(aes(x=eps.y, y=RMSE.est, group=AnaMethod, col=AnaMethod)) +
  geom_ribbon(aes(x=eps.y, ymax=RMSE.up, ymin=RMSE.lo, fill=AnaMethod), linetype=2,alpha=.05) +
  geom_line() +
  geom_point() +
  scale_x_discrete("Random error Y") +
  scale_y_continuous("RMSE") +
  facet_nested(eps.g ~SparsMethod + dg.thresh) +
  theme_bw() +
  theme(text = element_text(size=12))
```

<br>

```{r, echo=F, warning=F, message=F, fig.align='center', fig.width=10, fig.height=8, fig.cap="Nested line plot for RMSE assessing changes due to varying noise levels in maximal sample size and node size"}
tbl_scens %>%
  filter(n==500 & p==100 & ThreshMethod=="bin") %>%
  mutate_at(vars(beta.params, SparsMethod, AnaMethod), as.factor) %>%
  ggplot(aes(x=eps.y, y=RMSE.est, group=AnaMethod, col=AnaMethod)) +
  geom_ribbon(aes(x=eps.y, ymax=RMSE.up, ymin=RMSE.lo, fill=AnaMethod), linetype=2,alpha=.05) +
  geom_line() +
  geom_point() +
  scale_x_discrete("Random error Y") +
  scale_y_continuous("RMSE") +
  facet_nested(eps.g ~SparsMethod + dg.thresh) +
  theme_bw() +
  theme(text = element_text(size=12))
```



## R2

```{r, echo=F, warning=F, message=F, fig.align='center', fig.width=8, fig.height=8, fig.cap="Nested loop plot for R2 with noise of Y = 0"}
tbl_loo1 <- tbl_scens %>%
  filter(ThreshMethod == "bin" & eps.y==0 & SparsMethod == "weight-based") %>%
  dplyr::select(n, p, dg.thresh, eps.g,AnaMethod, R2.est) %>%
  pivot_wider(id_cols = c(n, p, dg.thresh, eps.g), names_from = AnaMethod, values_from = R2.est) %>% 
  mutate(n = as.factor(n))

p = nested_loop_plot(resdf = tbl_loo1,
                     x = "n", steps = "eps.g",
                     grid_rows = "p", grid_cols = "dg.thresh",
                     steps_y_base = -0.05, steps_y_height = 0.025,
                     x_name = "Sample size", y_name = "R2",
                     spu_x_shift = 1.5,
                     ylim = c(0,1), y_breaks = seq(0,1,0.25),
                     colors = scales::brewer_pal(palette = "Dark2"),
                     steps_values_annotate = TRUE, steps_annotation_size = 2.5,
                     hline_intercept = 0,
                     y_expand_add = c(0.2, 0.05),
                     post_processing = list(
                         add_custom_theme = list(
                           text=element_text(size=12),
                             axis.text.x = element_text(angle = -90,
                                                        vjust = 0.5,
                                                        size = 8)
                         )
                     ))
print(p)
```

<br>

```{r, echo=F, warning=F, message=F, fig.align='center', fig.width=10, fig.height=8, fig.cap="Nested line plot for R2 for DG threshold scenario single"}
tbl_scens %>%
  filter(eps.y==0 & ThreshMethod=="bin" & dg.thresh == "single") %>%
  mutate_at(vars(beta.params, SparsMethod, AnaMethod), as.factor) %>%
  ggplot(aes(x=n, y=R2.est, group=AnaMethod, col=AnaMethod)) +
  geom_ribbon(aes(x=n, ymax=R2.up, ymin=R2.lo, fill=AnaMethod), linetype=2,alpha=.05) +
  geom_line() +
  geom_point() +
  scale_x_discrete("Sample size") +
  scale_y_continuous("R2") +
  facet_nested(p ~SparsMethod+ eps.g) +
  theme_bw() +
  theme(text = element_text(size=12))
```

<br>

```{r, echo=F, warning=F, message=F, fig.align='center', fig.width=10, fig.height=8, fig.cap="Nested line plot for R2 for DG threshold scenario random"}
tbl_scens %>%
  filter(eps.y==0 & ThreshMethod=="bin" & dg.thresh == "random") %>%
  mutate_at(vars(beta.params, SparsMethod, AnaMethod), as.factor) %>%
  ggplot(aes(x=n, y=R2.est, group=AnaMethod, col=AnaMethod)) +
  geom_ribbon(aes(x=n, ymax=R2.up, ymin=R2.lo, fill=AnaMethod), linetype=2,alpha=.05) +
  geom_line() +
  geom_point() +
  scale_x_discrete("Sample size") +
  scale_y_continuous("R2") +
  facet_nested(p ~SparsMethod+ eps.g) +
  theme_bw() +
  theme(text = element_text(size=12))
```

<br>


```{r, echo=F, warning=F, message=F, fig.align='center', fig.width=10, fig.height=8, fig.cap="Nested line plot for R2 for DG threshold scenario single"}
tbl_scens %>%
  filter(eps.y==0 & ThreshMethod=="bin" & dg.thresh == "quadratic") %>%
  mutate_at(vars(beta.params, SparsMethod, AnaMethod), as.factor) %>%
  ggplot(aes(x=n, y=R2.est, group=AnaMethod, col=AnaMethod)) +
  geom_ribbon(aes(x=n, ymax=R2.up, ymin=R2.lo, fill=AnaMethod), linetype=2,alpha=.05) +
  geom_line() +
  geom_point() +
  scale_x_discrete("Sample size") +
  scale_y_continuous("R2") +
  facet_nested(p ~SparsMethod+ eps.g) +
  theme_bw() +
  theme(text = element_text(size=12))
```

<br>


```{r, echo=F, warning=F, message=F, fig.align='center', fig.width=10, fig.height=8, fig.cap="Nested line plot for R2 for all DG threshold scenarios and no noise for Y or G"}
tbl_scens %>%
  filter(eps.y==0 & eps.g==0 & ThreshMethod=="bin") %>%
  mutate_at(vars(beta.params, SparsMethod, AnaMethod), as.factor) %>%
  ggplot(aes(x=n, y=R2.est, group=AnaMethod, col=AnaMethod)) +
  geom_ribbon(aes(x=n, ymax=R2.up, ymin=R2.lo, fill=AnaMethod), linetype=2,alpha=.05) +
  geom_line() +
  geom_point() +
  scale_x_discrete("Sample size") +
  scale_y_continuous("R2") +
  facet_nested(p ~SparsMethod + dg.thresh) +
  theme_bw() +
  theme(text = element_text(size=12))
```

```{r, echo=F, warning=F, message=F, fig.align='center', fig.width=10, fig.height=8, fig.cap="Nested line plot for R2 for all DG threshold scenarios and maximal noise for Y (epsY=1) and G (epsG=0.1)"}
tbl_scens %>%
  filter(eps.y==1 & eps.g==0.1 & ThreshMethod=="bin") %>%
  mutate_at(vars(beta.params, SparsMethod, AnaMethod), as.factor) %>%
  ggplot(aes(x=n, y=R2.est, group=AnaMethod, col=AnaMethod)) +
  geom_ribbon(aes(x=n, ymax=R2.up, ymin=R2.lo, fill=AnaMethod), linetype=2,alpha=.05) +
  geom_line() +
  geom_point() +
  scale_x_discrete("Sample size") +
  scale_y_continuous("R2") +
  facet_nested(p ~SparsMethod + dg.thresh) +
  theme_bw() +
  theme(text = element_text(size=12))
```

```{r, echo=F, warning=F, message=F, fig.align='center', fig.width=10, fig.height=8, fig.cap="Nested line plot for R2 assessing changes due to varying noise levels in minimal sample size and node size"}
tbl_scens %>%
  filter(n==100 & p==50 & ThreshMethod=="bin") %>%
  mutate_at(vars(beta.params, SparsMethod, AnaMethod), as.factor) %>%
  ggplot(aes(x=eps.y, y=R2.est, group=AnaMethod, col=AnaMethod)) +
  geom_ribbon(aes(x=eps.y, ymax=R2.up, ymin=R2.lo, fill=AnaMethod), linetype=2,alpha=.05) +
  geom_line() +
  geom_point() +
  scale_x_discrete("Random error Y") +
  scale_y_continuous("R2") +
  facet_nested(eps.g ~SparsMethod + dg.thresh) +
  theme_bw() +
  theme(text = element_text(size=12))
```

<br>

```{r, echo=F, warning=F, message=F, fig.align='center', fig.width=10, fig.height=8, fig.cap="Nested line plot for R2 assessing changes due to varying noise levels in maximal sample size and node size"}
tbl_scens %>%
  filter(n==500 & p==100 & ThreshMethod=="bin") %>%
  mutate_at(vars(beta.params, SparsMethod, AnaMethod), as.factor) %>%
  ggplot(aes(x=eps.y, y=R2.est, group=AnaMethod, col=AnaMethod)) +
  geom_ribbon(aes(x=eps.y, ymax=R2.up, ymin=R2.lo, fill=AnaMethod), linetype=2,alpha=.05) +
  geom_line() +
  geom_point() +
  scale_x_discrete("Random error Y") +
  scale_y_continuous("R2") +
  facet_nested(eps.g ~SparsMethod + dg.thresh) +
  theme_bw() +
  theme(text = element_text(size=12))
```

