# ============================================================================ #
# Author: MG
# Date: 07.02.2021
# Info: Simulation study - Setup
# ============================================================================ #


# ======================= Packages & Code ======================================
if(!("pacman" %in% installed.packages())){install.packages("pacman")}
if(!("BiocManager" %in% installed.packages())){install.packages("BiocManager")}
if(!("WGCNA" %in% installed.packages())){BiocManager::install("WGCNA")}
if(!("GO.db" %in% installed.packages())){BiocManager::install("GO.db")}
if(!("looplot" %in% installed.packages())){devtools::install_github("matherealize/looplot")}

pacman::p_load(mvtnorm, Rcpp, MASS, Matrix, igraph,
               kableExtra, ggplot2, ggh4x, forcats, gridExtra, ggnewscale, here,
               stringr, future.apply, parallel, dplyr,  tidyr, knitr, reshape2,
               refund, broom, cvTools, concreg,  purrr, openxlsx, Hmisc,
               dtplyr, profvis, matrixStats, looplot, corpcor, hrbrthemes)
options(dplyr.summarise.inform = FALSE)
sourceCpp(here::here("src","utils.cpp"))



## ======================== Parameters =========================================
#set.seed(666)

# Paths
sim.date <- Sys.Date()
sim.file <- paste0("sim_", sim.date,"/")
sim.path <- here::here("output", sim.file)

source(here::here("src", "functions_main.R"))
source(here::here("src", "functions_aux.R"))

# -- Data generation
iter = 10                                                                       # iter: number of simulation iterations
p = 150                                                                         # p: number of biomarker nodes
q = 2                                                                           # q: number of covariates; 
b0 = 10                                                                         # b0: intercept for model
b1 = 15                                                                         # b1: coefficients for network features 
b2 = NA                                                                         # b2: coefficient in multiv. modelling
step.size = 0.01                                                                # step.size: step size for sequential thresholding

# Varying parameters
n = c(75, 150, 300)                                                             # n: sample size
setting = c("uni", "latent")                                                     # setting: univariable or multivariable modelling
outcome = c("prognostic","diagnostic")                                                       # outcome: diagnostic = latent variable generating individuality in networks; prognostic = generated by graph feature
network.model = c("block")                                                      # network.model: underlying default network structure
dg.spars = c("weight-based")                                                    # dg.spars: weight-based data
dg.thresh = list("single"=c(0.25),                                              # dg.thresh: sparsification threshold for data gen
                 "random"=c(0.1,0.4),
                 "flat"="flat",
                 "half-sine"="half-sine",
                 "sine"="sine")                                   
epslevel.y = c("none", "medium", "high")                                        # error term sigma_Y (outcome)
epslevel.g = c("none", "medium", "high")                                        # error term sigma_G (graph)

# -- Parameter distribution for edge weights ~ beta(a,b)
beta.params = list(c(1.5,6))                                                    # shape params of beta distribution
alpha0.params = list("norm"=c("mean"=10, "sd"=1.5))                             # stat params of normal distributed alpha0
alpha12.params = list("unif"=c("min"=0, "max"=2))                               # stat params of uniform distributed alpha1 and alpha2
Z1.params = list("norm"=c("mean"=0, "sd"=0.5))                                  # stat params of normal distributed latent processes Z1 and Z2
Z2.params = list("binom"=0.5)                                                   # stat params of normal distributed latent processes Z1 and Z2
excel = F                                                                       # generate additional excel file with scen results

scenarios <- expand.grid(
  iter = iter,
  n = n,
  q = q,
  p = p,
  setting = setting,
  outcome = outcome,
  network.model=network.model,
  dg.spars = dg.spars,
  dg.thresh = dg.thresh,
  beta.params = beta.params,
  alpha0.params = alpha0.params,
  alpha12.params = alpha12.params,
  Z1.params = Z1.params,
  Z2.params = Z2.params,
  b0 = b0,
  b1 = b1,
  b2 = b2,
  epslevel.y = epslevel.y,
  epslevel.g = epslevel.g,
  step.size = step.size,
  excel = excel 
)

# Manual changes to scenarios
scenarios <- scenarios %>%
  arrange(outcome,setting, n) %>%
  mutate(eps.y = 0,
         eps.g = 0) %>%
  mutate(eps.y = case_when(names(dg.thresh) %in% c("sine") & epslevel.y %in% "medium" ~ 0.75,
                                    names(dg.thresh) %in% c("sine") & epslevel.y %in% "high"~ 1.5,
                                    names(dg.thresh) %in% c("half-sine") & epslevel.y %in% "medium" ~ 0.5,
                                    names(dg.thresh) %in% c("half-sine") & epslevel.y %in% "high"~ 1,
                                    names(dg.thresh) %in% c("random") & epslevel.y %in% "medium" ~ 2.5,
                                    names(dg.thresh) %in% c("random") & epslevel.y %in% "high"~ 5,
                                    names(dg.thresh) %in% c("flat") & epslevel.y %in% "medium" ~ 2.5,
                                    names(dg.thresh) %in% c("flat") & epslevel.y %in% "high"~ 5,
                                    names(dg.thresh) %in% c("single") & epslevel.y %in% "medium" ~ 2,
                                    names(dg.thresh) %in% c("single") & epslevel.y %in% "high"~ 4,
                                    TRUE ~ 0),
         eps.g = case_when(names(dg.thresh) %in% c("random") & epslevel.g %in% "medium" ~ 0.5,
                           names(dg.thresh) %in% c("random") & epslevel.g %in% "high" ~ 1,
                           names(dg.thresh) %in% c("single", "flat", "sine") & epslevel.g %in% "medium" ~ 0.3,
                           names(dg.thresh) %in% c("single", "flat", "sine") & epslevel.g %in% "high" ~ 0.6,
                           names(dg.thresh) %in% c("half-sine") & epslevel.g %in% "medium" ~ 0.15,
                           names(dg.thresh) %in% c("half-sine") & epslevel.g %in% "high" ~ 0.3,
                           TRUE ~ 0),         
         eps.y = case_when(setting %in% "latent" & names(dg.thresh) %in% c("single")~ eps.y*1,
                           setting %in% "latent" & names(dg.thresh) %in% c("random")~ eps.y*1.25,
                           setting %in% "latent" & names(dg.thresh) %in% c("flat")~ eps.y*1,
                           setting %in% "latent" & names(dg.thresh) %in% c("sine")~ eps.y*1,
                           setting %in% "latent" & names(dg.thresh) %in% c("half-sine")~ eps.y*0.75,
                           TRUE ~eps.y),
         eps.g = case_when(setting %in% "latent" & names(dg.thresh) %in% c("single", "random") ~ eps.g*2,
                           setting %in% "latent" & epslevel.g %in% "medium" & names(dg.thresh) %in% c("flat") ~ 1.5,
                           setting %in% "latent" & epslevel.g %in% "high" & names(dg.thresh) %in% c("flat") ~ 3,
                           setting %in% "latent" & epslevel.g %in% "medium" & names(dg.thresh) %in% c("sine", "half-sine") ~ 5,
                           setting %in% "latent" & epslevel.g %in% "high" & names(dg.thresh) %in% c("sine", "half-sine") ~ 10,
                           TRUE ~eps.g)) %>%
  group_by(outcome,n, setting, epslevel.g, epslevel.y, network.model) %>%
  filter(!(duplicated(dg.spars) & outcome %in% "diagnostic")) %>%
  filter(!(outcome=="diagnostic" & epslevel.y=="medium"))%>%
  filter(!(outcome=="diagnostic" & setting=="uni"))%>%
  mutate(eps.g = case_when(outcome  %in% "diagnostic" ~ eps.g*2,
                           TRUE ~ eps.g))

print(paste0("Total number of scenarios to be evaluated = ", nrow(scenarios)))

