# ============================================================================ #
# Author: MG
# Date: 07.02.2021
# Info: Simulation study - Setup
# ============================================================================ #


# ======================= Packages & Code ======================================
if(!("pacman" %in% installed.packages())){install.packages("pacman")}
if(!("BiocManager" %in% installed.packages())){install.packages("BiocManager")}
if(!("WGCNA" %in% installed.packages())){BiocManager::install("WGCNA")}
if(!("GO.db" %in% installed.packages())){BiocManager::install("GO.db")}
if(!("looplot" %in% installed.packages())){devtools::install_github("matherealize/looplot")}

pacman::p_load(Rcpp, MASS, igraph, kableExtra, ggplot2, ggh4x, forcats, 
               gridExtra, ggnewscale, here, stringr, future.apply, parallel, 
               dplyr,  tidyr, knitr, reshape2, refund, purrr, openxlsx, Hmisc, 
               dtplyr, matrixStats, looplot)
options(dplyr.summarise.inform = FALSE)
sourceCpp(here::here("src","utils.cpp"))



## ======================== Parameters =========================================
#set.seed(666)

# Paths
sim.date <- Sys.Date()
sim.file <- paste0("sim_", sim.date,"/")
sim.path <- here::here("output", sim.file)

source(here::here("src", "functions_main.R"))
source(here::here("src", "functions_aux.R"))


## ========================= Prognostic setting ===================

# -- Parameter distribution for network
beta.params = list(c(1.3,6))                                                    # shape params of beta distribution
alpha0.params = list("norm"=c("mean"=10, "sd"=1.5))                             # stat params of normal distributed alpha0
alpha12.params = list("unif"=c("min"=0, "max"=2))                               # stat params of uniform distributed alpha1 and alpha2
Z1.params = list("norm"=c("mean"=0, "sd"=0.5))                                  # stat params of normal distributed latent processes Z1 and Z2
Z2.params = list("binom"=0.5)                                                   # stat params of normal distributed latent processes Z1 and Z2

# -- Data generation
iter = 10                                                                       # iter: number of simulation iterations
p = 150                                                                         # p: number of biomarker nodes
q = 2                                                                           # q: number of covariates; 
b0 = 10                                                                         # b0: intercept for model
b1 = 15                                                                         # b1: coefficients for network features 
b2 = NA                                                                         # b2: coefficient in multiv. modelling
step.size = 0.01                                                                # step.size: step size for sequential thresholding

# Varying parameters
n = c(75, 150, 300)                                                             # n: sample size
setting = c("uni", "latent")                                                     # setting: univariable or multivariable modelling
outcome = "prognostic"                                                          # outcome: diagnostic = latent variable generating individuality in networks; prognostic = generated by graph feature
dg.thresh = list("single"=c(0.25),                                              # dg.thresh: sparsification threshold for data gen
                 "random"=c(0.1,0.4),
                 "flat"="flat",
                 "half-sine"="half-sine",
                 "sine"="sine")                                   
epslevel.y = c("none", "medium", "high")                                        # error term sigma_Y (outcome)
epslevel.g = c("none", "medium", "high")                                        # error term sigma_G (graph)

scenarios <- expand.grid(
  iter = iter,
  n = n,
  q = q,
  p = p,
  setting = setting,
  outcome = outcome,
  dg.thresh = dg.thresh,
  beta.params = beta.params,
  alpha0.params = alpha0.params,
  alpha12.params = alpha12.params,
  Z1.params = Z1.params,
  Z2.params = Z2.params,
  b0 = b0,
  b1 = b1,
  b2 = b2,
  epslevel.y = epslevel.y,
  epslevel.g = epslevel.g,
  step.size = step.size)

# Manual changes to scenarios
scenarios.prognostic <- scenarios %>%
  arrange(outcome,setting, n) %>%
  mutate(eps.y = 0,
         eps.g = 0) %>%
  mutate(eps.y = case_when(names(dg.thresh) %in% c("single", "flat", "half-sine", "sine") & epslevel.y %in% "medium" ~ 2,
                           names(dg.thresh) %in% c("single", "flat", "half-sine", "sine") & epslevel.y %in% "high"~ 4,
                           names(dg.thresh) %in% c("random") & epslevel.y %in% "medium" ~ 2.5,
                           names(dg.thresh) %in% c("random") & epslevel.y %in% "high"~ 5,
                           TRUE ~ 0),
         eps.g = case_when(names(dg.thresh) %in% c("random") & epslevel.g %in% "medium" ~ 0.5,
                           names(dg.thresh) %in% c("random") & epslevel.g %in% "high" ~ 1,
                           names(dg.thresh) %in% c("single", "flat", "half-sine", "sine") & epslevel.g %in% "medium" ~ 0.5,
                           names(dg.thresh) %in% c("single", "flat", "half-sine", "sine") & epslevel.g %in% "high" ~ 1,
                           TRUE ~ 0),         
         eps.y = case_when(setting %in% "latent" & names(dg.thresh) %in% c("single", "random","flat", "half-sine","sine")~ eps.y*1.25,
                           TRUE ~eps.y),      
         eps.y = case_when(setting %in% "multi" & names(dg.thresh) %in% c("single", "random","flat", "half-sine","sine")~ eps.y*1.5,
                           TRUE ~eps.y))




## ========================= Diagnostic setting ===========================
# -- Data generation
outcome = "diagnostic"                                                          # outcome: diagnostic = latent variable generating individuality in networks; prognostic = generated by graph feature
b0 = b1 = b2 =NA                                                                
dg.thresh = NA                                  
setting = NA                                                                    # setting: univariable or multivariable modelling
epslevel.y = c("none", "medium", "high")                                        # error term sigma_Y (outcome)
epslevel.g = c("none", "medium", "high")                                        # error term sigma_G (graph)

scenarios <- expand.grid(
  iter = iter,
  n = n,
  q = q,
  p = p,
  setting = setting,
  outcome = outcome,
  dg.thresh = dg.thresh,
  beta.params = beta.params,
  alpha0.params = alpha0.params,
  alpha12.params = alpha12.params,
  Z1.params = Z1.params,
  Z2.params = Z2.params,
  b0 = b0,
  b1 = b1,
  b2 = b2,
  epslevel.y = epslevel.y,
  epslevel.g = epslevel.g,
  step.size = step.size
)

# Manual changes to scenarios
scenarios.diagnostic <- scenarios %>%
  arrange(outcome,setting, n) %>%
  mutate(eps.y = case_when(epslevel.y %in% "none" ~ 0,
                           epslevel.y %in% "medium" ~ 0.5,
                           epslevel.y %in% "high" ~ 1.5,
                           TRUE ~ 0),
         eps.g = case_when(epslevel.g %in% "none" ~ 0,
                           epslevel.g %in% "medium" ~ 0.4,
                           epslevel.g %in% "high" ~ 0.8,
                           TRUE ~ 0))
        
## ========= Combine Parameter settings =======================

scenarios <- rbind(scenarios.diagnostic, scenarios.prognostic)
#scenarios <- scenarios %>% filter(outcome %in% "prognostic")
print(paste0("Total number of scenarios to be evaluated = ", nrow(scenarios)))

